### ISSUE TITLE
Export files

### ISSUE THREAD

**Issue by lnoble237** [dawndiy/recorder#4]
Hi thanks for this great free software.

How do I export files? I can't see any option. Failing that, where are the files stored on Ubuntu touch?

Cheers

**Comment by dawndiy** [comment]
The App in Ubuntu Touch import/export files using Content-Hub like iOS. This App can as a source provider to export files to other Apps now, but can't initiative to export file to any other location you want  because of the permission policy of Ubuntu Touch OS. So you can import file from this App in other App, but can't initiative to export file in this App.

You can use File Manager App to find the record files in this App. The location of this files you can find at the 'file details dialog'. click No.2 button in image below.

![records](https://raw.githubusercontent.com/dawndiy/recorder/master/Recorder/image/intro_2.png)

**Comment by lnoble237** [comment]
thanks for your help, I just moved the file from the location to the music folder using the terminal and could access it from there
